optimizer:
  type: AdamW
  kwargs:
    lr: 0.001
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 5

dataset:
  train:
    _base_: cfgs/dataset_configs/ShapeNet-13.yaml
    others:
      subset: train
      npoints: 1024
  val:
    _base_: cfgs/dataset_configs/ShapeNet-13.yaml
    others:
      subset: test
      npoints: 1024

with_color: FALSE
ckpt_path: "classifier.pth"
npoints: 1024
total_bs: 32
step_per_update: 1
max_epoch: 100
