optimizer:
  type: AdamW
  kwargs:
    lr: 0.001
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 5

dataset:
  train:
    _base_: cfgs/dataset_configs/ShapeNet-13.yaml
    others:
      subset: train
      npoints: 8192
  val:
    _base_: cfgs/dataset_configs/ShapeNet-13.yaml
    others:
      subset: test
      npoints: 8192

model:
  NAME: VPP
  mode: coarse

  vqgan_config:
    resolution: 24
    base_dim: 64
    down_sample: 4
    codebook_dim: 256
    codebook_num: 2048
    with_se: TRUE
    ckpt_path: vqgan.pth

  voxel_config:
    depth: 12
    num_heads: 4
    noise_ratio: 0.0
    cfg_ratio: 1.0
    rand_ratio: 0.0
    image_text_ratio: 0.7

  prompt_encoder: ViT-B/32

# If you want to test FID and Acc during the training of the Voxel Semantic Generator,
# you must prepare the ckpt for the Point Upsampler and Classifier in advance,
# and refer to the instructions for inference.yaml and classifier.yaml.
validate:
  inference_cfg: cfgs/inference.yaml
  classifier_cfg: cfgs/classifier.yaml

with_color: FALSE
total_bs: 128
step_per_update: 1
max_epoch: 100