optimizer:
  type: Adam
  kwargs:
    lr: 0.0001
    weight_decay: 0.0001

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 0

dataset:
  train:
    _base_: cfgs/dataset_configs/ShapeNet-13.yaml
    others:
      subset: train
      npoints: 8192
  val:
    _base_: cfgs/dataset_configs/ShapeNet-13.yaml
    others:
      subset: test
      npoints: 8192

model:
  NAME: VQGAN
  resolution: 24
  base_dim: 64
  down_sample: 4
  codebook_dim: 256
  codebook_num: 2048
  beta: 1
  with_se: TRUE

discriminator:
  NAME: Discriminator
  base_dim: 64
  factor: 0.01
  start_epoch: 0
  with_se: TRUE

with_color: FALSE
npoints: 8192
total_bs: 128
step_per_update: 1
max_epoch: 100
