optimizer:
  type: AdamW
  kwargs:
    lr: 2e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: train
  val:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test
  test:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test

model:
  NAME: PointTransformer
  trans_dim: 384
  depth: 6
  cls_dim: 40
  num_heads: 6
  group_size: 32
  num_group: 64
  encoder_dims: 384
  type: full


npoints: 1024
total_bs: 32
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10
