optimizer:
  type: AdamW
  kwargs:
    lr: 0.001
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 5

dataset:
  train:
    _base_: cfgs/dataset_configs/Objaverse.yaml
    others:
      subset: 'train'
      npoints: 8192

model:
  NAME: VPP
  mode: smoother
  smooth_config:
    resolution: 24
    trans_dim: 64
    depth: 4
    num_heads: 4
    kl_ratio: 1.0

# If you want to test FID and Acc during the training of the Point Upsampler,
# you must prepare the ckpt for the Voxel Semantic Generator and Classifier in advance,
# and refer to the instructions for inference.yaml and classifier.yaml.
validate:
  inference_cfg: cfgs/inference.yaml
  classifier_cfg: cfgs/classifier.yaml

with_color: FALSE
npoints: 8192
total_bs: 512
step_per_update: 1
max_epoch: 100
