optimizer:
  type: AdamW
  kwargs:
    lr: 0.001
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: cfgs/dataset_configs/Objaverse.yaml
    others:
      subset: 'train'
      npoints: 1024

model:
  NAME: VPP
  mode: fine
  group_size: 32
  num_group: 64

  encoder_config:
    trans_dim: 384
    depth: 12
    num_heads: 6
    ckpt_path: pointmae.pth

  point_config:
    trans_dim: 384
    depth: 6
    num_heads: 6

  decoder_depth: 4
  decoder_num_heads: 6

# If you want to test FID and Acc during the training of the Point Upsampler,
# you must prepare the ckpt for the Voxel Semantic Generator and Classifier in advance,
# and refer to the instructions for inference.yaml and classifier.yaml.
validate:
  inference_cfg: cfgs/inference.yaml
  classifier_cfg: cfgs/classifier.yaml

with_color: FALSE
npoints: 1024
total_bs: 512
step_per_update: 1
max_epoch: 300
